services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      # - clickhouse-server
    env_file:
      - .env

  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: uzairyasin123
      MYSQL_DATABASE: my_database
      MYSQL_USER: uzair
      MYSQL_PASSWORD: uzairyasin123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # clickhouse-server:
  #   image: clickhouse/clickhouse-server:latest
  #   container_name: clickhouse-server
  #   restart: always
  #   environment:
  #     - CLICKHOUSE_USER=default
  #     - CLICKHOUSE_PASSWORD=uzairyasin123
  #   ports:
  #     - "8123:8123"
  #     - "9000:9000"
  #   volumes:
  #     - clickhouse_data:/var/lib/clickhouse

volumes:
  mysql_data:
  # clickhouse_data:
