services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - HOSTED_MYSQL_URL="mysql+pymysql://uzair:uzairyasin123@54.152.153.225:3307/my_database"
      - HOSTED_CLICKHOUSE_URL="clickhouse://default@54.152.153.225:9000/default"
        # PORT
      -  PORT=8000
        # SENTRY DSN
      -  SENTRY_DSN="https://51d84b96e556490bb0e17bc4c95f7cc9@o4509756111060992.ingest.us.sentry.io/4509756114075648"
  
  
